<?php

namespace App\Support\Authorization;

use App\Enums\PermissionName as P;
use App\Enums\UserRole;

final class RolePermissionMap
{
    /** @return array<string, list<string>> */
    public static function all(): array
    {
        return [
            UserRole::SUPER_ADMIN->value => P::values(),
            UserRole::MANAGER->value => P::values(),
            UserRole::SUPERVISOR->value => self::values([
                P::ADMIN_ACCESS,
                P::DASHBOARD_VIEW,
                P::DASHBOARD_FINANCIAL,
                P::DASHBOARD_OPERATIONAL,
                P::AREAS_VIEW,
                P::EMPLOYEES_VIEW,
                P::CUSTOMERS_VIEW,
                P::DISTRIBUTION_ROUTES_VIEW,
                P::VEHICLES_VIEW,
                P::WAREHOUSES_VIEW,
                P::STOCK_BALANCES_VIEW,
                P::VEHICLE_LOADS_VIEW,
                P::VEHICLE_LOADS_CREATE,
                P::VEHICLE_LOADS_UPDATE,
                P::VEHICLE_LOADS_APPROVE,
                P::VEHICLE_LOADS_PRINT,
                P::SALES_INVOICES_VIEW,
                P::SALES_INVOICES_CREATE,
                P::SALES_INVOICES_UPDATE,
                P::SALES_INVOICES_CONFIRM,
                P::SALES_INVOICES_PRINT,
                P::SALES_RETURNS_VIEW,
                P::SALES_RETURNS_CREATE,
                P::SALES_RETURNS_UPDATE,
                P::SALES_RETURNS_CONFIRM,
                P::SALES_RETURNS_PRINT,
                P::CUSTOMER_PAYMENTS_VIEW,
                P::CUSTOMER_PAYMENTS_CREATE,
                P::CUSTOMER_PAYMENTS_UPDATE,
                P::CUSTOMER_PAYMENTS_CONFIRM,
                P::CUSTOMER_PAYMENTS_PRINT,
                P::VEHICLE_EXPENSES_VIEW,
                P::VEHICLE_EXPENSES_CREATE,
                P::VEHICLE_EXPENSES_UPDATE,
                P::VEHICLE_EXPENSES_APPROVE,
                P::VEHICLE_EXPENSES_REJECT,
                P::VEHICLE_EXPENSES_PRINT,
                P::DAILY_CLOSINGS_VIEW,
                P::DAILY_CLOSINGS_CREATE,
                P::DAILY_CLOSINGS_UPDATE,
                P::DAILY_CLOSINGS_REFRESH_TOTALS,
                P::DAILY_CLOSINGS_CONFIRM,
                P::DAILY_CLOSINGS_PRINT,
                P::REPORT_SALES,
                P::REPORT_CUSTOMER_PAYMENTS,
                P::REPORT_CUSTOMER_STATEMENT,
                P::REPORT_DAILY_CLOSINGS,
                P::REPORT_VEHICLE_LOADS,
                P::REPORT_VEHICLE_STOCK,
                P::REPORT_SALES_RETURNS,
                P::REPORT_PROFIT,
                P::REPORT_VEHICLE_EXPENSES,
                P::REPORT_EXPIRY_RISK,
                P::REPORT_OVERDUE_CUSTOMERS,
                P::REPORT_TOP_CUSTOMERS,
                P::REPORT_ROUTE_PERFORMANCE,
            ]),
            UserRole::WAREHOUSE_KEEPER->value => self::values([
                P::ADMIN_ACCESS,
                P::DASHBOARD_VIEW,
                P::DASHBOARD_OPERATIONAL,
                P::PRODUCT_CATEGORIES_VIEW,
                P::PRODUCTS_VIEW,
                P::UNITS_VIEW,
                P::DISTRIBUTION_ROUTES_VIEW,
                P::VEHICLES_VIEW,
                P::WAREHOUSES_VIEW,
                P::STOCK_BALANCES_VIEW,
                P::STOCK_MOVEMENTS_VIEW,
                P::STOCK_MOVEMENTS_CREATE,
                P::STOCK_MOVEMENTS_UPDATE,
                P::VEHICLE_LOADS_VIEW,
                P::VEHICLE_LOADS_CREATE,
                P::VEHICLE_LOADS_UPDATE,
                P::VEHICLE_LOADS_APPROVE,
                P::VEHICLE_LOADS_PRINT,
                P::REPORT_VEHICLE_LOADS,
                P::REPORT_VEHICLE_STOCK,
                P::REPORT_EXPIRY_RISK,
            ]),
            UserRole::ACCOUNTANT->value => self::values([
                P::ADMIN_ACCESS,
                P::DASHBOARD_VIEW,
                P::DASHBOARD_FINANCIAL,
                P::CUSTOMERS_VIEW,
                P::SALES_INVOICES_VIEW,
                P::SALES_INVOICES_PRINT,
                P::SALES_RETURNS_VIEW,
                P::SALES_RETURNS_PRINT,
                P::CUSTOMER_PAYMENTS_VIEW,
                P::CUSTOMER_PAYMENTS_CREATE,
                P::CUSTOMER_PAYMENTS_UPDATE,
                P::CUSTOMER_PAYMENTS_CONFIRM,
                P::CUSTOMER_PAYMENTS_CANCEL,
                P::CUSTOMER_PAYMENTS_PRINT,
                P::VEHICLE_EXPENSES_VIEW,
                P::VEHICLE_EXPENSES_PRINT,
                P::DAILY_CLOSINGS_VIEW,
                P::DAILY_CLOSINGS_CREATE,
                P::DAILY_CLOSINGS_UPDATE,
                P::DAILY_CLOSINGS_REFRESH_TOTALS,
                P::DAILY_CLOSINGS_CONFIRM,
                P::DAILY_CLOSINGS_PRINT,
                P::REPORT_SALES,
                P::REPORT_CUSTOMER_PAYMENTS,
                P::REPORT_CUSTOMER_STATEMENT,
                P::REPORT_DAILY_CLOSINGS,
                P::REPORT_SALES_RETURNS,
                P::REPORT_PROFIT,
                P::REPORT_VEHICLE_EXPENSES,
                P::REPORT_OVERDUE_CUSTOMERS,
                P::REPORT_TOP_CUSTOMERS,
                P::REPORT_ROUTE_PERFORMANCE,
            ]),
            UserRole::SALES_REPRESENTATIVE->value => self::values([
                P::CUSTOMERS_VIEW,
                P::STOCK_BALANCES_VIEW,
                P::VEHICLE_LOADS_VIEW,
                P::SALES_INVOICES_VIEW,
                P::SALES_INVOICES_CREATE,
                P::SALES_INVOICES_UPDATE,
                P::SALES_RETURNS_VIEW,
                P::SALES_RETURNS_CREATE,
                P::SALES_RETURNS_UPDATE,
                P::CUSTOMER_PAYMENTS_VIEW,
                P::CUSTOMER_PAYMENTS_CREATE,
                P::CUSTOMER_PAYMENTS_UPDATE,
                P::VEHICLE_EXPENSES_VIEW,
                P::VEHICLE_EXPENSES_CREATE,
                P::VEHICLE_EXPENSES_UPDATE,
            ]),
            UserRole::DRIVER->value => self::values([
                P::STOCK_BALANCES_VIEW,
                P::VEHICLE_LOADS_VIEW,
                P::VEHICLE_EXPENSES_VIEW,
                P::VEHICLE_EXPENSES_CREATE,
                P::VEHICLE_EXPENSES_UPDATE,
            ]),
        ];
    }

    /** @param list<P> $permissions
     *  @return list<string>
     */
    private static function values(array $permissions): array
    {
        return array_map(
            fn (P $permission): string => $permission->value,
            $permissions,
        );
    }
}
